// Canonical team → home-stadium name lists used by the League Completionist
// badges in the Stats tab and the Leagues passport tracker. Names reflect
// current (as of this writing) stadium branding; sponsorship renames happen
// often, so update the `stadium` field when a venue is renamed rather than
// treating this as permanently accurate.
//
// LA Rams/Chargers share SoFi Stadium and the Giants/Jets share MetLife
// Stadium, so a single visit there will satisfy both teams' entries — there's
// no way to tell which team's game it was from the venue name alone.

export const LEAGUE_STADIUMS = {
  MLB: [
    { team: 'Arizona Diamondbacks',  stadium: 'Chase Field',                     city: 'Phoenix, Arizona' },
    { team: 'Atlanta Braves',        stadium: 'Truist Park',                     city: 'Atlanta, Georgia' },
    { team: 'Baltimore Orioles',     stadium: 'Oriole Park at Camden Yards',     city: 'Baltimore, Maryland' },
    { team: 'Boston Red Sox',        stadium: 'Fenway Park',                     city: 'Boston, Massachusetts' },
    { team: 'Chicago Cubs',          stadium: 'Wrigley Field',                   city: 'Chicago, Illinois' },
    { team: 'Chicago White Sox',     stadium: 'Rate Field',                      city: 'Chicago, Illinois' },
    { team: 'Cincinnati Reds',       stadium: 'Great American Ball Park',        city: 'Cincinnati, Ohio' },
    { team: 'Cleveland Guardians',   stadium: 'Progressive Field',               city: 'Cleveland, Ohio' },
    { team: 'Colorado Rockies',      stadium: 'Coors Field',                     city: 'Denver, Colorado' },
    { team: 'Detroit Tigers',        stadium: 'Comerica Park',                   city: 'Detroit, Michigan' },
    { team: 'Houston Astros',        stadium: 'Daikin Park',                     city: 'Houston, Texas' },
    { team: 'Kansas City Royals',    stadium: 'Kauffman Stadium',                city: 'Kansas City, Missouri' },
    { team: 'Los Angeles Angels',    stadium: 'Angel Stadium',                   city: 'Anaheim, California' },
    { team: 'Los Angeles Dodgers',   stadium: 'Dodger Stadium',                  city: 'Los Angeles, California' },
    { team: 'Miami Marlins',         stadium: 'loanDepot Park',                  city: 'Miami, Florida' },
    { team: 'Milwaukee Brewers',     stadium: 'American Family Field',           city: 'Milwaukee, Wisconsin' },
    { team: 'Minnesota Twins',       stadium: 'Target Field',                    city: 'Minneapolis, Minnesota' },
    { team: 'New York Mets',         stadium: 'Citi Field',                      city: 'New York, New York' },
    { team: 'New York Yankees',      stadium: 'Yankee Stadium',                  city: 'New York, New York' },
    { team: 'Oakland Athletics',     stadium: 'Sutter Health Park',              city: 'West Sacramento, California' },
    { team: 'Philadelphia Phillies', stadium: 'Citizens Bank Park',              city: 'Philadelphia, Pennsylvania' },
    { team: 'Pittsburgh Pirates',    stadium: 'PNC Park',                        city: 'Pittsburgh, Pennsylvania' },
    { team: 'San Diego Padres',      stadium: 'Petco Park',                      city: 'San Diego, California' },
    { team: 'San Francisco Giants',  stadium: 'Oracle Park',                     city: 'San Francisco, California' },
    { team: 'Seattle Mariners',      stadium: 'T-Mobile Park',                   city: 'Seattle, Washington' },
    { team: 'St. Louis Cardinals',   stadium: 'Busch Stadium',                   city: 'St. Louis, Missouri' },
    { team: 'Tampa Bay Rays',        stadium: 'Tropicana Field',                 city: 'St. Petersburg, Florida' },
    { team: 'Texas Rangers',         stadium: 'Globe Life Field',                city: 'Arlington, Texas' },
    { team: 'Toronto Blue Jays',     stadium: 'Rogers Centre',                   city: 'Toronto, Ontario' },
    { team: 'Washington Nationals',  stadium: 'Nationals Park',                  city: 'Washington, D.C.' },
  ],

  NFL: [
    { team: 'Arizona Cardinals',     stadium: 'State Farm Stadium',              city: 'Glendale, Arizona' },
    { team: 'Atlanta Falcons',       stadium: 'Mercedes-Benz Stadium',           city: 'Atlanta, Georgia' },
    { team: 'Baltimore Ravens',      stadium: 'M&T Bank Stadium',                city: 'Baltimore, Maryland' },
    { team: 'Buffalo Bills',         stadium: 'Highmark Stadium',                city: 'Orchard Park, New York' },
    { team: 'Carolina Panthers',     stadium: 'Bank of America Stadium',         city: 'Charlotte, North Carolina' },
    { team: 'Chicago Bears',         stadium: 'Soldier Field',                   city: 'Chicago, Illinois' },
    { team: 'Cincinnati Bengals',    stadium: 'Paycor Stadium',                  city: 'Cincinnati, Ohio' },
    { team: 'Cleveland Browns',      stadium: 'Huntington Bank Field',           city: 'Cleveland, Ohio' },
    { team: 'Dallas Cowboys',        stadium: 'AT&T Stadium',                    city: 'Arlington, Texas' },
    { team: 'Denver Broncos',        stadium: 'Empower Field at Mile High',      city: 'Denver, Colorado' },
    { team: 'Detroit Lions',         stadium: 'Ford Field',                      city: 'Detroit, Michigan' },
    { team: 'Green Bay Packers',     stadium: 'Lambeau Field',                   city: 'Green Bay, Wisconsin' },
    { team: 'Houston Texans',        stadium: 'NRG Stadium',                     city: 'Houston, Texas' },
    { team: 'Indianapolis Colts',    stadium: 'Lucas Oil Stadium',               city: 'Indianapolis, Indiana' },
    { team: 'Jacksonville Jaguars',  stadium: 'EverBank Stadium',                city: 'Jacksonville, Florida' },
    { team: 'Kansas City Chiefs',    stadium: 'Arrowhead Stadium',               city: 'Kansas City, Missouri' },
    { team: 'Las Vegas Raiders',     stadium: 'Allegiant Stadium',               city: 'Las Vegas, Nevada' },
    { team: 'Los Angeles Chargers',  stadium: 'SoFi Stadium',                    city: 'Inglewood, California' },
    { team: 'Los Angeles Rams',      stadium: 'SoFi Stadium',                    city: 'Inglewood, California' },
    { team: 'Miami Dolphins',        stadium: 'Hard Rock Stadium',               city: 'Miami Gardens, Florida' },
    { team: 'Minnesota Vikings',     stadium: 'U.S. Bank Stadium',               city: 'Minneapolis, Minnesota' },
    { team: 'New England Patriots',  stadium: 'Gillette Stadium',                city: 'Foxborough, Massachusetts' },
    { team: 'New Orleans Saints',    stadium: 'Caesars Superdome',               city: 'New Orleans, Louisiana' },
    { team: 'New York Giants',       stadium: 'MetLife Stadium',                 city: 'East Rutherford, New Jersey' },
    { team: 'New York Jets',         stadium: 'MetLife Stadium',                 city: 'East Rutherford, New Jersey' },
    { team: 'Philadelphia Eagles',   stadium: 'Lincoln Financial Field',         city: 'Philadelphia, Pennsylvania' },
    { team: 'Pittsburgh Steelers',   stadium: 'Acrisure Stadium',                city: 'Pittsburgh, Pennsylvania' },
    { team: 'San Francisco 49ers',   stadium: "Levi's Stadium",                  city: 'Santa Clara, California' },
    { team: 'Seattle Seahawks',      stadium: 'Lumen Field',                     city: 'Seattle, Washington' },
    { team: 'Tampa Bay Buccaneers',  stadium: 'Raymond James Stadium',           city: 'Tampa, Florida' },
    { team: 'Tennessee Titans',      stadium: 'Nissan Stadium',                  city: 'Nashville, Tennessee' },
    { team: 'Washington Commanders', stadium: 'Northwest Stadium',               city: 'Landover, Maryland' },
  ],

  // Power 4 conference realignment has been in flux for a few seasons —
  // membership below reflects the 2026 season (SEC 16, Big Ten 18, Big 12 16,
  // ACC 17). Notre Dame is excluded: it's a football independent with only a
  // partial ACC scheduling agreement, not a full conference member.
  // Miami/Pitt share stadiums with NFL tenants (Dolphins, Steelers) — same
  // shared-venue caveat as the NFL SoFi/MetLife entries above.
  CFB: [
    // ── SEC ──
    { team: 'Alabama Crimson Tide',      stadium: 'Bryant-Denny Stadium',                    city: 'Tuscaloosa, Alabama' },
    { team: 'Arkansas Razorbacks',       stadium: 'Donald W. Reynolds Razorback Stadium',    city: 'Fayetteville, Arkansas' },
    { team: 'Auburn Tigers',             stadium: 'Jordan-Hare Stadium',                     city: 'Auburn, Alabama' },
    { team: 'Florida Gators',            stadium: 'Ben Hill Griffin Stadium',                city: 'Gainesville, Florida' },
    { team: 'Georgia Bulldogs',          stadium: 'Sanford Stadium',                         city: 'Athens, Georgia' },
    { team: 'Kentucky Wildcats',         stadium: 'Kroger Field',                            city: 'Lexington, Kentucky' },
    { team: 'LSU Tigers',                stadium: 'Tiger Stadium',                           city: 'Baton Rouge, Louisiana' },
    { team: 'Mississippi State Bulldogs',stadium: 'Davis Wade Stadium',                      city: 'Starkville, Mississippi' },
    { team: 'Missouri Tigers',           stadium: 'Faurot Field at Memorial Stadium',        city: 'Columbia, Missouri' },
    { team: 'Ole Miss Rebels',           stadium: 'Vaught-Hemingway Stadium',                city: 'Oxford, Mississippi' },
    { team: 'Oklahoma Sooners',          stadium: 'Gaylord Family Oklahoma Memorial Stadium',city: 'Norman, Oklahoma' },
    { team: 'South Carolina Gamecocks',  stadium: 'Williams-Brice Stadium',                  city: 'Columbia, South Carolina' },
    { team: 'Tennessee Volunteers',      stadium: 'Neyland Stadium',                         city: 'Knoxville, Tennessee' },
    { team: 'Texas Longhorns',           stadium: 'Darrell K Royal-Texas Memorial Stadium',  city: 'Austin, Texas' },
    { team: 'Texas A&M Aggies',          stadium: 'Kyle Field',                              city: 'College Station, Texas' },
    { team: 'Vanderbilt Commodores',     stadium: 'FirstBank Stadium',                       city: 'Nashville, Tennessee' },

    // ── Big Ten ──
    { team: 'Illinois Fighting Illini',  stadium: 'Memorial Stadium',                        city: 'Champaign, Illinois' },
    { team: 'Indiana Hoosiers',          stadium: 'Memorial Stadium',                         city: 'Bloomington, Indiana' },
    { team: 'Iowa Hawkeyes',             stadium: 'Kinnick Stadium',                          city: 'Iowa City, Iowa' },
    { team: 'Maryland Terrapins',        stadium: 'SECU Stadium',                             city: 'College Park, Maryland' },
    { team: 'Michigan Wolverines',       stadium: 'Michigan Stadium',                         city: 'Ann Arbor, Michigan' },
    { team: 'Michigan State Spartans',   stadium: 'Spartan Stadium',                          city: 'East Lansing, Michigan' },
    { team: 'Minnesota Golden Gophers',  stadium: 'Huntington Bank Stadium',                  city: 'Minneapolis, Minnesota' },
    { team: 'Nebraska Cornhuskers',      stadium: 'Memorial Stadium',                         city: 'Lincoln, Nebraska' },
    { team: 'Northwestern Wildcats',     stadium: 'Ryan Field',                               city: 'Evanston, Illinois' },
    { team: 'Ohio State Buckeyes',       stadium: 'Ohio Stadium',                             city: 'Columbus, Ohio' },
    { team: 'Oregon Ducks',              stadium: 'Autzen Stadium',                           city: 'Eugene, Oregon' },
    { team: 'Penn State Nittany Lions',  stadium: 'Beaver Stadium',                           city: 'University Park, Pennsylvania' },
    { team: 'Purdue Boilermakers',       stadium: 'Ross-Ade Stadium',                         city: 'West Lafayette, Indiana' },
    { team: 'Rutgers Scarlet Knights',   stadium: 'SHI Stadium',                              city: 'Piscataway, New Jersey' },
    { team: 'UCLA Bruins',               stadium: 'Rose Bowl',                                city: 'Pasadena, California' },
    { team: 'USC Trojans',               stadium: 'United Airlines Field at LA Memorial Coliseum', city: 'Los Angeles, California' },
    { team: 'Washington Huskies',        stadium: 'Alaska Airlines Field at Husky Stadium',   city: 'Seattle, Washington' },
    { team: 'Wisconsin Badgers',         stadium: 'Camp Randall Stadium',                     city: 'Madison, Wisconsin' },

    // ── Big 12 ──
    { team: 'Arizona Wildcats',          stadium: 'Casino Del Sol Stadium',                  city: 'Tucson, Arizona' },
    { team: 'Arizona State Sun Devils',  stadium: 'Mountain America Stadium',                city: 'Tempe, Arizona' },
    { team: 'Baylor Bears',              stadium: 'McLane Stadium',                          city: 'Waco, Texas' },
    { team: 'BYU Cougars',               stadium: 'LaVell Edwards Stadium',                  city: 'Provo, Utah' },
    { team: 'Cincinnati Bearcats',       stadium: 'Nippert Stadium',                         city: 'Cincinnati, Ohio' },
    { team: 'Colorado Buffaloes',        stadium: 'Folsom Field',                            city: 'Boulder, Colorado' },
    { team: 'Houston Cougars',           stadium: 'TDECU Stadium',                           city: 'Houston, Texas' },
    { team: 'Iowa State Cyclones',       stadium: 'Jack Trice Stadium',                       city: 'Ames, Iowa' },
    { team: 'Kansas Jayhawks',           stadium: 'David Booth Kansas Memorial Stadium',      city: 'Lawrence, Kansas' },
    { team: 'Kansas State Wildcats',     stadium: 'Bill Snyder Family Stadium',               city: 'Manhattan, Kansas' },
    { team: 'Oklahoma State Cowboys',    stadium: 'Boone Pickens Stadium',                    city: 'Stillwater, Oklahoma' },
    { team: 'TCU Horned Frogs',          stadium: 'Amon G. Carter Stadium',                   city: 'Fort Worth, Texas' },
    { team: 'Texas Tech Red Raiders',    stadium: 'Jones AT&T Stadium',                       city: 'Lubbock, Texas' },
    { team: 'UCF Knights',               stadium: 'FBC Mortgage Stadium',                     city: 'Orlando, Florida' },
    { team: 'Utah Utes',                 stadium: 'Rice-Eccles Stadium',                      city: 'Salt Lake City, Utah' },
    { team: 'West Virginia Mountaineers',stadium: 'Milan Puskar Stadium',                     city: 'Morgantown, West Virginia' },

    // ── ACC ──
    { team: 'Boston College Eagles',     stadium: 'Alumni Stadium',                          city: 'Chestnut Hill, Massachusetts' },
    { team: 'California Golden Bears',   stadium: 'California Memorial Stadium',             city: 'Berkeley, California' },
    { team: 'Clemson Tigers',            stadium: 'Memorial Stadium',                         city: 'Clemson, South Carolina' },
    { team: 'Duke Blue Devils',          stadium: 'Wallace Wade Stadium',                     city: 'Durham, North Carolina' },
    { team: 'Florida State Seminoles',   stadium: 'Doak Campbell Stadium',                    city: 'Tallahassee, Florida' },
    { team: 'Georgia Tech Yellow Jackets', stadium: 'Bobby Dodd Stadium',                     city: 'Atlanta, Georgia' },
    { team: 'Louisville Cardinals',      stadium: 'L&N Federal Credit Union Stadium',         city: 'Louisville, Kentucky' },
    { team: 'Miami Hurricanes',          stadium: 'Hard Rock Stadium',                        city: 'Miami Gardens, Florida' },
    { team: 'NC State Wolfpack',         stadium: 'Carter-Finley Stadium',                    city: 'Raleigh, North Carolina' },
    { team: 'North Carolina Tar Heels',  stadium: 'Kenan Memorial Stadium',                   city: 'Chapel Hill, North Carolina' },
    { team: 'Pittsburgh Panthers',       stadium: 'Acrisure Stadium',                         city: 'Pittsburgh, Pennsylvania' },
    { team: 'SMU Mustangs',              stadium: 'Gerald J. Ford Stadium',                   city: 'Dallas, Texas' },
    { team: 'Stanford Cardinal',         stadium: 'Stanford Stadium',                         city: 'Stanford, California' },
    { team: 'Syracuse Orange',           stadium: 'JMA Wireless Dome',                        city: 'Syracuse, New York' },
    { team: 'Virginia Cavaliers',        stadium: 'Scott Stadium',                            city: 'Charlottesville, Virginia' },
    { team: 'Virginia Tech Hokies',      stadium: 'Lane Stadium',                             city: 'Blacksburg, Virginia' },
    { team: 'Wake Forest Demon Deacons', stadium: 'Allegacy Federal Credit Union Stadium',    city: 'Winston-Salem, North Carolina' },
  ],

  NBA: [
    { team: 'Atlanta Hawks',          stadium: 'State Farm Arena',               city: 'Atlanta, Georgia' },
    { team: 'Boston Celtics',         stadium: 'TD Garden',                      city: 'Boston, Massachusetts' },
    { team: 'Brooklyn Nets',          stadium: 'Barclays Center',                city: 'Brooklyn, New York' },
    { team: 'Charlotte Hornets',      stadium: 'Spectrum Center',                city: 'Charlotte, North Carolina' },
    { team: 'Chicago Bulls',          stadium: 'United Center',                  city: 'Chicago, Illinois' },
    { team: 'Cleveland Cavaliers',    stadium: 'Rocket Arena',                   city: 'Cleveland, Ohio' },
    { team: 'Dallas Mavericks',       stadium: 'American Airlines Center',       city: 'Dallas, Texas' },
    { team: 'Denver Nuggets',         stadium: 'Ball Arena',                     city: 'Denver, Colorado' },
    { team: 'Detroit Pistons',        stadium: 'Little Caesars Arena',           city: 'Detroit, Michigan' },
    { team: 'Golden State Warriors',  stadium: 'Chase Center',                   city: 'San Francisco, California' },
    { team: 'Houston Rockets',        stadium: 'Toyota Center',                  city: 'Houston, Texas' },
    { team: 'Indiana Pacers',         stadium: 'Gainbridge Fieldhouse',          city: 'Indianapolis, Indiana' },
    { team: 'LA Clippers',            stadium: 'Intuit Dome',                    city: 'Inglewood, California' },
    { team: 'Los Angeles Lakers',     stadium: 'Crypto.com Arena',               city: 'Los Angeles, California' },
    { team: 'Memphis Grizzlies',      stadium: 'FedExForum',                     city: 'Memphis, Tennessee' },
    { team: 'Miami Heat',             stadium: 'Kaseya Center',                  city: 'Miami, Florida' },
    { team: 'Milwaukee Bucks',        stadium: 'Fiserv Forum',                   city: 'Milwaukee, Wisconsin' },
    { team: 'Minnesota Timberwolves', stadium: 'Target Center',                  city: 'Minneapolis, Minnesota' },
    { team: 'New Orleans Pelicans',   stadium: 'Smoothie King Center',           city: 'New Orleans, Louisiana' },
    { team: 'New York Knicks',        stadium: 'Madison Square Garden',          city: 'New York, New York' },
    { team: 'Oklahoma City Thunder',  stadium: 'Paycom Center',                  city: 'Oklahoma City, Oklahoma' },
    { team: 'Orlando Magic',          stadium: 'Kia Center',                     city: 'Orlando, Florida' },
    { team: 'Philadelphia 76ers',     stadium: 'Wells Fargo Center',             city: 'Philadelphia, Pennsylvania' },
    { team: 'Phoenix Suns',           stadium: 'Footprint Center',               city: 'Phoenix, Arizona' },
    { team: 'Portland Trail Blazers', stadium: 'Moda Center',                    city: 'Portland, Oregon' },
    { team: 'Sacramento Kings',       stadium: 'Golden 1 Center',                city: 'Sacramento, California' },
    { team: 'San Antonio Spurs',      stadium: 'Frost Bank Center',              city: 'San Antonio, Texas' },
    { team: 'Toronto Raptors',        stadium: 'Scotiabank Arena',               city: 'Toronto, Ontario' },
    { team: 'Utah Jazz',              stadium: 'Delta Center',                   city: 'Salt Lake City, Utah' },
    { team: 'Washington Wizards',     stadium: 'Capital One Arena',              city: 'Washington, D.C.' },
  ],

  NHL: [
    { team: 'Anaheim Ducks',          stadium: 'Honda Center',                   city: 'Anaheim, California' },
    { team: 'Utah Mammoth',           stadium: 'Delta Center',                   city: 'Salt Lake City, Utah' },
    { team: 'Boston Bruins',          stadium: 'TD Garden',                      city: 'Boston, Massachusetts' },
    { team: 'Buffalo Sabres',         stadium: 'KeyBank Center',                 city: 'Buffalo, New York' },
    { team: 'Calgary Flames',         stadium: 'Scotiabank Saddledome',          city: 'Calgary, Alberta' },
    { team: 'Carolina Hurricanes',    stadium: 'Lenovo Center',                  city: 'Raleigh, North Carolina' },
    { team: 'Chicago Blackhawks',     stadium: 'United Center',                  city: 'Chicago, Illinois' },
    { team: 'Colorado Avalanche',     stadium: 'Ball Arena',                     city: 'Denver, Colorado' },
    { team: 'Columbus Blue Jackets',  stadium: 'Nationwide Arena',               city: 'Columbus, Ohio' },
    { team: 'Dallas Stars',           stadium: 'American Airlines Center',       city: 'Dallas, Texas' },
    { team: 'Detroit Red Wings',      stadium: 'Little Caesars Arena',           city: 'Detroit, Michigan' },
    { team: 'Edmonton Oilers',        stadium: 'Rogers Place',                   city: 'Edmonton, Alberta' },
    { team: 'Florida Panthers',       stadium: 'Amerant Bank Arena',             city: 'Sunrise, Florida' },
    { team: 'Los Angeles Kings',      stadium: 'Crypto.com Arena',               city: 'Los Angeles, California' },
    { team: 'Minnesota Wild',         stadium: 'Xcel Energy Center',             city: 'St. Paul, Minnesota' },
    { team: 'Montreal Canadiens',     stadium: 'Bell Centre',                    city: 'Montreal, Quebec' },
    { team: 'Nashville Predators',    stadium: 'Bridgestone Arena',              city: 'Nashville, Tennessee' },
    { team: 'New Jersey Devils',      stadium: 'Prudential Center',              city: 'Newark, New Jersey' },
    { team: 'New York Islanders',     stadium: 'UBS Arena',                      city: 'Elmont, New York' },
    { team: 'New York Rangers',       stadium: 'Madison Square Garden',          city: 'New York, New York' },
    { team: 'Ottawa Senators',        stadium: 'Canadian Tire Centre',           city: 'Ottawa, Ontario' },
    { team: 'Philadelphia Flyers',    stadium: 'Wells Fargo Center',             city: 'Philadelphia, Pennsylvania' },
    { team: 'Pittsburgh Penguins',    stadium: 'PPG Paints Arena',               city: 'Pittsburgh, Pennsylvania' },
    { team: 'San Jose Sharks',        stadium: 'SAP Center',                     city: 'San Jose, California' },
    { team: 'Seattle Kraken',         stadium: 'Climate Pledge Arena',           city: 'Seattle, Washington' },
    { team: 'St. Louis Blues',        stadium: 'Enterprise Center',              city: 'St. Louis, Missouri' },
    { team: 'Tampa Bay Lightning',    stadium: 'Amalie Arena',                   city: 'Tampa, Florida' },
    { team: 'Toronto Maple Leafs',    stadium: 'Scotiabank Arena',               city: 'Toronto, Ontario' },
    { team: 'Vancouver Canucks',      stadium: 'Rogers Arena',                   city: 'Vancouver, British Columbia' },
    { team: 'Vegas Golden Knights',   stadium: 'T-Mobile Arena',                 city: 'Las Vegas, Nevada' },
    { team: 'Washington Capitals',    stadium: 'Capital One Arena',              city: 'Washington, D.C.' },
    { team: 'Winnipeg Jets',          stadium: 'Canada Life Centre',             city: 'Winnipeg, Manitoba' },
  ],

  MLS: [
    { team: 'Atlanta United FC',      stadium: 'Mercedes-Benz Stadium',          city: 'Atlanta, Georgia' },
    { team: 'Austin FC',              stadium: 'Q2 Stadium',                     city: 'Austin, Texas' },
    { team: 'Charlotte FC',           stadium: 'Bank of America Stadium',        city: 'Charlotte, North Carolina' },
    { team: 'Chicago Fire FC',        stadium: 'Soldier Field',                  city: 'Chicago, Illinois' },
    { team: 'FC Cincinnati',          stadium: 'TQL Stadium',                    city: 'Cincinnati, Ohio' },
    { team: 'Colorado Rapids',        stadium: "Dick's Sporting Goods Park",     city: 'Commerce City, Colorado' },
    { team: 'Columbus Crew',          stadium: 'Lower.com Field',                city: 'Columbus, Ohio' },
    { team: 'D.C. United',            stadium: 'Audi Field',                     city: 'Washington, D.C.' },
    { team: 'FC Dallas',              stadium: 'Toyota Stadium',                 city: 'Frisco, Texas' },
    { team: 'Houston Dynamo FC',      stadium: 'Shell Energy Stadium',           city: 'Houston, Texas' },
    { team: 'Inter Miami CF',         stadium: 'Chase Stadium',                  city: 'Fort Lauderdale, Florida' },
    { team: 'LA Galaxy',              stadium: 'Dignity Health Sports Park',     city: 'Carson, California' },
    { team: 'Los Angeles FC',         stadium: 'BMO Stadium',                    city: 'Los Angeles, California' },
    { team: 'Minnesota United FC',    stadium: 'Allianz Field',                  city: 'Saint Paul, Minnesota' },
    { team: 'CF Montréal',            stadium: 'Stade Saputo',                   city: 'Montreal, Quebec' },
    { team: 'Nashville SC',           stadium: 'Geodis Park',                    city: 'Nashville, Tennessee' },
    { team: 'New England Revolution', stadium: 'Gillette Stadium',               city: 'Foxborough, Massachusetts' },
    { team: 'New York City FC',       stadium: 'Yankee Stadium',                 city: 'New York, New York' },
    { team: 'New York Red Bulls',     stadium: 'Red Bull Arena',                 city: 'Harrison, New Jersey' },
    { team: 'Orlando City SC',        stadium: 'Inter&Co Stadium',               city: 'Orlando, Florida' },
    { team: 'Philadelphia Union',     stadium: 'Subaru Park',                    city: 'Chester, Pennsylvania' },
    { team: 'Portland Timbers',       stadium: 'Providence Park',                city: 'Portland, Oregon' },
    { team: 'Real Salt Lake',         stadium: 'America First Field',            city: 'Sandy, Utah' },
    { team: 'San Jose Earthquakes',   stadium: 'PayPal Park',                    city: 'San Jose, California' },
    { team: 'Seattle Sounders FC',    stadium: 'Lumen Field',                    city: 'Seattle, Washington' },
    { team: 'Sporting Kansas City',   stadium: "Children's Mercy Park",          city: 'Kansas City, Kansas' },
    { team: 'St. Louis City SC',      stadium: 'CITYPARK',                       city: 'St. Louis, Missouri' },
    { team: 'Toronto FC',             stadium: 'BMO Field',                      city: 'Toronto, Ontario' },
    { team: 'Vancouver Whitecaps FC', stadium: 'BC Place',                       city: 'Vancouver, British Columbia' },
  ],

  WNBA: [
    { team: 'Atlanta Dream',          stadium: 'Gateway Center Arena',           city: 'College Park, Georgia' },
    { team: 'Chicago Sky',            stadium: 'Wintrust Arena',                 city: 'Chicago, Illinois' },
    { team: 'Connecticut Sun',        stadium: 'Mohegan Sun Arena',              city: 'Uncasville, Connecticut' },
    { team: 'Dallas Wings',           stadium: 'College Park Center',            city: 'Arlington, Texas' },
    { team: 'Golden State Valkyries', stadium: 'Chase Center',                   city: 'San Francisco, California' },
    { team: 'Indiana Fever',          stadium: 'Gainbridge Fieldhouse',          city: 'Indianapolis, Indiana' },
    { team: 'Las Vegas Aces',         stadium: 'Michelob ULTRA Arena',           city: 'Las Vegas, Nevada' },
    { team: 'Los Angeles Sparks',     stadium: 'Crypto.com Arena',               city: 'Los Angeles, California' },
    { team: 'Minnesota Lynx',         stadium: 'Target Center',                  city: 'Minneapolis, Minnesota' },
    { team: 'New York Liberty',       stadium: 'Barclays Center',                city: 'Brooklyn, New York' },
    { team: 'Phoenix Mercury',        stadium: 'PHX Arena',                      city: 'Phoenix, Arizona' },
    { team: 'Seattle Storm',          stadium: 'Climate Pledge Arena',           city: 'Seattle, Washington' },
    { team: 'Washington Mystics',     stadium: 'CareFirst Arena',                city: 'Washington, D.C.' },
    { team: 'Toronto Tempo',          stadium: 'Coca-Cola Coliseum',             city: 'Toronto, Ontario' },
  ],
};

export const LEAGUE_ICONS = {
  MLB: '⚾', NFL: '🏈', NBA: '🏀', NHL: '🏒', MLS: '⚽', WNBA: '🏀', CFB: '🎓',
};

export const LEAGUE_KEYS = Object.keys(LEAGUE_STADIUMS);
