// Canonical team → home-stadium name lists used by the League Completionist
// badges in the Stats tab. Names reflect current (as of this writing) stadium
// branding; sponsorship renames happen often, so update the `stadium` field
// when a venue is renamed rather than treating this as permanently accurate.
//
// LA Rams/Chargers share SoFi Stadium and the Giants/Jets share MetLife
// Stadium, so a single visit there will satisfy both teams' entries — there's
// no way to tell which team's game it was from the venue name alone.

export const LEAGUE_STADIUMS = {
  MLB: [
    { team: 'Arizona Diamondbacks',  stadium: 'Chase Field' },
    { team: 'Atlanta Braves',        stadium: 'Truist Park' },
    { team: 'Baltimore Orioles',     stadium: 'Oriole Park at Camden Yards' },
    { team: 'Boston Red Sox',        stadium: 'Fenway Park' },
    { team: 'Chicago Cubs',          stadium: 'Wrigley Field' },
    { team: 'Chicago White Sox',     stadium: 'Rate Field' },
    { team: 'Cincinnati Reds',       stadium: 'Great American Ball Park' },
    { team: 'Cleveland Guardians',   stadium: 'Progressive Field' },
    { team: 'Colorado Rockies',      stadium: 'Coors Field' },
    { team: 'Detroit Tigers',        stadium: 'Comerica Park' },
    { team: 'Houston Astros',        stadium: 'Daikin Park' },
    { team: 'Kansas City Royals',    stadium: 'Kauffman Stadium' },
    { team: 'Los Angeles Angels',    stadium: 'Angel Stadium' },
    { team: 'Los Angeles Dodgers',   stadium: 'Dodger Stadium' },
    { team: 'Miami Marlins',         stadium: 'loanDepot Park' },
    { team: 'Milwaukee Brewers',     stadium: 'American Family Field' },
    { team: 'Minnesota Twins',       stadium: 'Target Field' },
    { team: 'New York Mets',         stadium: 'Citi Field' },
    { team: 'New York Yankees',      stadium: 'Yankee Stadium' },
    { team: 'Oakland Athletics',     stadium: 'Sutter Health Park' },
    { team: 'Philadelphia Phillies', stadium: 'Citizens Bank Park' },
    { team: 'Pittsburgh Pirates',    stadium: 'PNC Park' },
    { team: 'San Diego Padres',      stadium: 'Petco Park' },
    { team: 'San Francisco Giants',  stadium: 'Oracle Park' },
    { team: 'Seattle Mariners',      stadium: 'T-Mobile Park' },
    { team: 'St. Louis Cardinals',   stadium: 'Busch Stadium' },
    { team: 'Tampa Bay Rays',        stadium: 'Tropicana Field' },
    { team: 'Texas Rangers',         stadium: 'Globe Life Field' },
    { team: 'Toronto Blue Jays',     stadium: 'Rogers Centre' },
    { team: 'Washington Nationals',  stadium: 'Nationals Park' },
  ],

  NFL: [
    { team: 'Arizona Cardinals',     stadium: 'State Farm Stadium' },
    { team: 'Atlanta Falcons',       stadium: 'Mercedes-Benz Stadium' },
    { team: 'Baltimore Ravens',      stadium: 'M&T Bank Stadium' },
    { team: 'Buffalo Bills',         stadium: 'Highmark Stadium' },
    { team: 'Carolina Panthers',     stadium: 'Bank of America Stadium' },
    { team: 'Chicago Bears',         stadium: 'Soldier Field' },
    { team: 'Cincinnati Bengals',    stadium: 'Paycor Stadium' },
    { team: 'Cleveland Browns',      stadium: 'Huntington Bank Field' },
    { team: 'Dallas Cowboys',        stadium: 'AT&T Stadium' },
    { team: 'Denver Broncos',        stadium: 'Empower Field at Mile High' },
    { team: 'Detroit Lions',         stadium: 'Ford Field' },
    { team: 'Green Bay Packers',     stadium: 'Lambeau Field' },
    { team: 'Houston Texans',        stadium: 'NRG Stadium' },
    { team: 'Indianapolis Colts',    stadium: 'Lucas Oil Stadium' },
    { team: 'Jacksonville Jaguars',  stadium: 'EverBank Stadium' },
    { team: 'Kansas City Chiefs',    stadium: 'Arrowhead Stadium' },
    { team: 'Las Vegas Raiders',     stadium: 'Allegiant Stadium' },
    { team: 'Los Angeles Chargers',  stadium: 'SoFi Stadium' },
    { team: 'Los Angeles Rams',      stadium: 'SoFi Stadium' },
    { team: 'Miami Dolphins',        stadium: 'Hard Rock Stadium' },
    { team: 'Minnesota Vikings',     stadium: 'U.S. Bank Stadium' },
    { team: 'New England Patriots',  stadium: 'Gillette Stadium' },
    { team: 'New Orleans Saints',    stadium: 'Caesars Superdome' },
    { team: 'New York Giants',       stadium: 'MetLife Stadium' },
    { team: 'New York Jets',         stadium: 'MetLife Stadium' },
    { team: 'Philadelphia Eagles',   stadium: 'Lincoln Financial Field' },
    { team: 'Pittsburgh Steelers',   stadium: 'Acrisure Stadium' },
    { team: 'San Francisco 49ers',   stadium: "Levi's Stadium" },
    { team: 'Seattle Seahawks',      stadium: 'Lumen Field' },
    { team: 'Tampa Bay Buccaneers',  stadium: 'Raymond James Stadium' },
    { team: 'Tennessee Titans',      stadium: 'Nissan Stadium' },
    { team: 'Washington Commanders', stadium: 'Northwest Stadium' },
  ],

  NBA: [
    { team: 'Atlanta Hawks',         stadium: 'State Farm Arena' },
    { team: 'Boston Celtics',        stadium: 'TD Garden' },
    { team: 'Brooklyn Nets',         stadium: 'Barclays Center' },
    { team: 'Charlotte Hornets',     stadium: 'Spectrum Center' },
    { team: 'Chicago Bulls',         stadium: 'United Center' },
    { team: 'Cleveland Cavaliers',   stadium: 'Rocket Arena' },
    { team: 'Dallas Mavericks',      stadium: 'American Airlines Center' },
    { team: 'Denver Nuggets',        stadium: 'Ball Arena' },
    { team: 'Detroit Pistons',       stadium: 'Little Caesars Arena' },
    { team: 'Golden State Warriors', stadium: 'Chase Center' },
    { team: 'Houston Rockets',       stadium: 'Toyota Center' },
    { team: 'Indiana Pacers',        stadium: 'Gainbridge Fieldhouse' },
    { team: 'LA Clippers',           stadium: 'Intuit Dome' },
    { team: 'Los Angeles Lakers',    stadium: 'Crypto.com Arena' },
    { team: 'Memphis Grizzlies',     stadium: 'FedExForum' },
    { team: 'Miami Heat',            stadium: 'Kaseya Center' },
    { team: 'Milwaukee Bucks',       stadium: 'Fiserv Forum' },
    { team: 'Minnesota Timberwolves',stadium: 'Target Center' },
    { team: 'New Orleans Pelicans',  stadium: 'Smoothie King Center' },
    { team: 'New York Knicks',       stadium: 'Madison Square Garden' },
    { team: 'Oklahoma City Thunder', stadium: 'Paycom Center' },
    { team: 'Orlando Magic',         stadium: 'Kia Center' },
    { team: 'Philadelphia 76ers',    stadium: 'Wells Fargo Center' },
    { team: 'Phoenix Suns',          stadium: 'Footprint Center' },
    { team: 'Portland Trail Blazers',stadium: 'Moda Center' },
    { team: 'Sacramento Kings',      stadium: 'Golden 1 Center' },
    { team: 'San Antonio Spurs',     stadium: 'Frost Bank Center' },
    { team: 'Toronto Raptors',       stadium: 'Scotiabank Arena' },
    { team: 'Utah Jazz',             stadium: 'Delta Center' },
    { team: 'Washington Wizards',    stadium: 'Capital One Arena' },
  ],

  NHL: [
    { team: 'Anaheim Ducks',          stadium: 'Honda Center' },
    { team: 'Utah Mammoth',           stadium: 'Delta Center' },
    { team: 'Boston Bruins',          stadium: 'TD Garden' },
    { team: 'Buffalo Sabres',         stadium: 'KeyBank Center' },
    { team: 'Calgary Flames',         stadium: 'Scotiabank Saddledome' },
    { team: 'Carolina Hurricanes',    stadium: 'Lenovo Center' },
    { team: 'Chicago Blackhawks',     stadium: 'United Center' },
    { team: 'Colorado Avalanche',     stadium: 'Ball Arena' },
    { team: 'Columbus Blue Jackets',  stadium: 'Nationwide Arena' },
    { team: 'Dallas Stars',           stadium: 'American Airlines Center' },
    { team: 'Detroit Red Wings',      stadium: 'Little Caesars Arena' },
    { team: 'Edmonton Oilers',        stadium: 'Rogers Place' },
    { team: 'Florida Panthers',       stadium: 'Amerant Bank Arena' },
    { team: 'Los Angeles Kings',      stadium: 'Crypto.com Arena' },
    { team: 'Minnesota Wild',         stadium: 'Xcel Energy Center' },
    { team: 'Montreal Canadiens',     stadium: 'Bell Centre' },
    { team: 'Nashville Predators',    stadium: 'Bridgestone Arena' },
    { team: 'New Jersey Devils',      stadium: 'Prudential Center' },
    { team: 'New York Islanders',     stadium: 'UBS Arena' },
    { team: 'New York Rangers',       stadium: 'Madison Square Garden' },
    { team: 'Ottawa Senators',        stadium: 'Canadian Tire Centre' },
    { team: 'Philadelphia Flyers',    stadium: 'Wells Fargo Center' },
    { team: 'Pittsburgh Penguins',    stadium: 'PPG Paints Arena' },
    { team: 'San Jose Sharks',        stadium: 'SAP Center' },
    { team: 'Seattle Kraken',         stadium: 'Climate Pledge Arena' },
    { team: 'St. Louis Blues',        stadium: 'Enterprise Center' },
    { team: 'Tampa Bay Lightning',    stadium: 'Amalie Arena' },
    { team: 'Toronto Maple Leafs',    stadium: 'Scotiabank Arena' },
    { team: 'Vancouver Canucks',      stadium: 'Rogers Arena' },
    { team: 'Vegas Golden Knights',   stadium: 'T-Mobile Arena' },
    { team: 'Washington Capitals',    stadium: 'Capital One Arena' },
    { team: 'Winnipeg Jets',          stadium: 'Canada Life Centre' },
  ],

  MLS: [
    { team: 'Atlanta United FC',       stadium: 'Mercedes-Benz Stadium' },
    { team: 'Austin FC',               stadium: 'Q2 Stadium' },
    { team: 'Charlotte FC',            stadium: 'Bank of America Stadium' },
    { team: 'Chicago Fire FC',         stadium: 'Soldier Field' },
    { team: 'FC Cincinnati',           stadium: 'TQL Stadium' },
    { team: 'Colorado Rapids',         stadium: "Dick's Sporting Goods Park" },
    { team: 'Columbus Crew',           stadium: 'Lower.com Field' },
    { team: 'D.C. United',             stadium: 'Audi Field' },
    { team: 'FC Dallas',               stadium: 'Toyota Stadium' },
    { team: 'Houston Dynamo FC',       stadium: 'Shell Energy Stadium' },
    { team: 'Inter Miami CF',          stadium: 'Chase Stadium' },
    { team: 'LA Galaxy',               stadium: 'Dignity Health Sports Park' },
    { team: 'Los Angeles FC',          stadium: 'BMO Stadium' },
    { team: 'Minnesota United FC',     stadium: 'Allianz Field' },
    { team: 'CF Montréal',             stadium: 'Stade Saputo' },
    { team: 'Nashville SC',            stadium: 'Geodis Park' },
    { team: 'New England Revolution',  stadium: 'Gillette Stadium' },
    { team: 'New York City FC',        stadium: 'Yankee Stadium' },
    { team: 'New York Red Bulls',      stadium: 'Red Bull Arena' },
    { team: 'Orlando City SC',         stadium: 'Inter&Co Stadium' },
    { team: 'Philadelphia Union',      stadium: 'Subaru Park' },
    { team: 'Portland Timbers',        stadium: 'Providence Park' },
    { team: 'Real Salt Lake',          stadium: 'America First Field' },
    { team: 'San Jose Earthquakes',    stadium: 'PayPal Park' },
    { team: 'Seattle Sounders FC',     stadium: 'Lumen Field' },
    { team: 'Sporting Kansas City',    stadium: "Children's Mercy Park" },
    { team: 'St. Louis City SC',       stadium: 'CITYPARK' },
    { team: 'Toronto FC',              stadium: 'BMO Field' },
    { team: 'Vancouver Whitecaps FC',  stadium: 'BC Place' },
  ],

  WNBA: [
    { team: 'Atlanta Dream',           stadium: 'Gateway Center Arena' },
    { team: 'Chicago Sky',             stadium: 'Wintrust Arena' },
    { team: 'Connecticut Sun',         stadium: 'Mohegan Sun Arena' },
    { team: 'Dallas Wings',            stadium: 'College Park Center' },
    { team: 'Golden State Valkyries',  stadium: 'Chase Center' },
    { team: 'Indiana Fever',           stadium: 'Gainbridge Fieldhouse' },
    { team: 'Las Vegas Aces',          stadium: 'Michelob ULTRA Arena' },
    { team: 'Los Angeles Sparks',      stadium: 'Crypto.com Arena' },
    { team: 'Minnesota Lynx',          stadium: 'Target Center' },
    { team: 'New York Liberty',        stadium: 'Barclays Center' },
    { team: 'Phoenix Mercury',         stadium: 'PHX Arena' },
    { team: 'Seattle Storm',           stadium: 'Climate Pledge Arena' },
    { team: 'Washington Mystics',      stadium: 'CareFirst Arena' },
    { team: 'Toronto Tempo',           stadium: 'Coca-Cola Coliseum' },
  ],
};
